# To run locally:
# act -P windows-latest=-self-hosted
# run_ci.bat
# Worked fine

name: Run tests

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup MSVC
    # TODO: Check version and explore updated versions
    # Specifically for using VS 2026
      uses: ilammy/msvc-dev-cmd@v1.13.0
      with:
        arch: x64

    - name: Get toolset info
      run: cl

    - name: Build and run only tests
      shell: cmd
      run: build.bat test-only
